/**
 * Namespace `Library.Circulation` of the "Library" test model:
 * members, copies, loans, branches - plus the complex types used by the operations.
 */
namespace Library.Circulation;

using {Library.Catalog} from './common';

// ---------------------------------------------------------------------------------------------
// Complex types (operation payloads)
// ---------------------------------------------------------------------------------------------

type OverdueNotice {
  Reason    : String;
  Amount    : Decimal(5, 2);
  CreatedAt : Timestamp;
}

type LoanStats {
  TotalLoans          : Int64;

  @odata.Type: 'Edm.Duration'
  AverageLoanDuration : String;
}

type BranchStats {
  BranchId  : Integer;
  LoanCount : Int64;
}

type AnnualReport {
  Year          : Integer;
  TotalLoans    : Int64;
  TotalLateFees : Decimal(12, 2);
}

type DateRange {
  /** `from` is a reserved CDL word - escaped, the OData property name stays `From`. */
  ![From] : Date;
  To      : Date;
}

// ---------------------------------------------------------------------------------------------
// Entities
// ---------------------------------------------------------------------------------------------

entity Member {
  /** Generated by the server unless the request brings one - see srv/handlers/keys.ts. */
  @Core.ComputedDefaultValue
  key Id                : Integer;
      Name              : String(100) not null;
      DateOfBirth       : Date;

      /** Flattened to Address_Street/City/PostalCode/Country - FEATURE-COVERAGE.md §2.1. */
      Address           : Catalog.PostalAddress;

      /** Collection of a complex type - this one *does* produce a real `<ComplexType>`. */
      PreviousAddresses : many Catalog.PostalAddress;

      /** Reference model: `Core.ComputedDefaultValue` - the client may send one, else the server fills in. */
      @Core.ComputedDefaultValue
      ActiveSince       : Timestamp;

      /**
       * Deliberately different facets from Loan.LateFee (Decimal 5,2).
       *
       * Reference model: `Core.Permissions` = `Read` - readable, never writable. The distinction against
       * `@Core.Computed` is what it says about *reading*, which is nothing in the computed case.
       */
      @Core.Permissions: #Read
      Balance           : Decimal(9, 2);

      Loans             : Composition of many Loan on Loans.Member = $self;
      Reservations      : Composition of many Reservation on Reservations.Member = $self;
      /**
       * A composition, unlike the other to-one relationships here: an identity document belongs to
       * exactly one member and has no life of its own, which is also why it should go when the member
       * does. EDMX cannot express the distinction, so the reference model's plain navigation property
       * permits either reading - this is the one place where the "part of" reading is the honest one.
       */
      IdDocument        : Composition of IdDocument;
}
// Bound operations: see srv/library-service.cds.

/**
 * Composite key (MediumId + InventoryNumber) as in the reference model.
 *
 * Follows from the aspect-based media hierarchy (FEATURE-COVERAGE.md §1.1): with no abstract base
 * type to point at, `MediumId` stays a bare Guid rather than a managed association. The media
 * entities carry an unmanaged `Copies` backlink over this column instead (see catalog.cds), so
 * `$expand=Copies` still works on all seven of them.
 */
entity Copy {
  key MediumId        : UUID;
  key InventoryNumber : Integer;

      /**
       * Reference model annotates the Copies set with Core.OptimisticConcurrency on Condition.
       * CAP's ETag handling is fully correct at runtime; only the emitted annotation is empty
       * rather than naming this property - FEATURE-COVERAGE.md §2.5.
       */
      @odata.etag
      Condition       : UInt8;

      IsLoanable      : Boolean not null default true;
      Status          : Catalog.AvailabilityStatus;
      AcquisitionDate : Date;

      /**
       * CDS has no single-precision float. The type override declares `Edm.Single` while storage
       * stays `Double`; values must be kept in single range to stay conformant - a complete
       * workaround, see FEATURE-COVERAGE.md §3.2.
       */
      @odata.Type   : 'Edm.Single'
      WeightKg        : Double;

      /**
       * Trailing underscore deliberately collides with the `Location` navigation property under a
       * client renaming strategy (odata2ts#142).
       * FEATURE-COVERAGE.md §2.5: `@odata.Unicode` is ignored by CAP - no `Unicode="false"` facet is emitted.
       */
      @odata.Unicode: false
      Location_       : String(10);

      Location        : Association to Branch;
}
// Bound operations: see srv/library-service.cds.

entity Loan {
  key Id         : UUID;

      /** Reference model: `Core.Immutable` - settable on insert, fixed from then on. */
      @Core.Immutable
      LoanedAt   : Timestamp not null;

      DueDate     : Date not null;

      /** Deliberately nullable: explicit-`null`-vs-absent-property test case (odata2ts#257/#218). */
      ReturnedAt : Timestamp;

      LateFee    : Decimal(5, 2);
      Member     : Association to Member not null;

      /** Composite foreign key -> renders two `<ReferentialConstraint>` entries. */
      Copy       : Association to Copy not null;
}
// Bound operations: see srv/library-service.cds.

entity Reservation {
  key Id        : UUID;
      ReservedAt : Timestamp;

      /**
       * Not in the reference model - required as the backlink target of `Member.Reservations`,
       * because CAP compositions need an explicit ON condition.
       */
      Member    : Association to Member;
}

entity IdDocument {
  key Id         : UUID;

      /** `Edm.Binary`: upload via PATCH, download via `.../Scan/$value`. */
      Scan       : Binary;

      UploadedAt : Timestamp;
}

entity Branch {
  /** Generated by the server unless the request brings one - see srv/handlers/keys.ts. */
  @Core.ComputedDefaultValue
  key Id              : Integer;
      Name            : String(100) not null;
      Address         : Catalog.PostalAddress;

      /**
       * CDS has no spatial types. The override puts the correct type and SRID in `$metadata`, but
       * the values stay WKT strings where OData expects GeoJSON - a cosmetic workaround only,
       * see FEATURE-COVERAGE.md §3.3.
       */
      @odata: {
        Type: 'Edm.GeographyPoint',
        SRID: 4326
      }
      Location        : String;

      @odata: {
        Type: 'Edm.GeographyPolygon',
        SRID: 4326
      }
      CatchmentArea   : String;

      /** CDS has no signed 8-bit integer; override + value range keeps it conformant (§3.2). */
      @odata.Type: 'Edm.SByte'
      LowestFloor     : Int16;

      @odata: {
        Type: 'Edm.GeometryPoint',
        SRID: 0
      }
      FloorPlanOrigin : String;

      @odata: {
        Type: 'Edm.GeometryCollection',
        SRID: 0
      }
      FloorPlanShapes : String;

      OpensAt         : Time;
      ClosesAt        : Time;
      Amenities       : Catalog.Amenities;
      Population      : Int64;
}

entity Bookmobile {
  /** Generated by the server unless the request brings one - see srv/handlers/keys.ts. */
  @Core.ComputedDefaultValue
  key Id              : Integer;
      LicensePlate    : String(12);

      @odata: {
        Type: 'Edm.GeographyLineString',
        SRID: 4326
      }
      Route           : String;

      @odata: {
        Type: 'Edm.GeographyPoint',
        SRID: 4326
      }
      CurrentPosition : String;
}
