/**
 * Namespace `PublisherRegistry` - a standalone namespace without the `Library.` prefix,
 * simulating an external system.
 *
 * FEATURE-COVERAGE.md §1.4: the reference model deliberately declares a second type named `Branch` here, distinct
 * from `Library.Circulation.Branch`. CAP renders *one* flat EDM schema per service, so both would
 * collide on the entity type name. The type is therefore called `PublisherBranch` here.
 *
 * The `Books` backlink to `Library.Catalog.Book` is added by catalog.cds via `extend`, to keep the
 * file dependencies acyclic.
 */
namespace PublisherRegistry;

entity Publisher {
  /** Generated by the server unless the request brings one - see srv/handlers/keys.ts. */
  @Core.ComputedDefaultValue
  key Id      : Integer;
      Name    : String(100) not null;
      Country : String(60);
      Founded : Date;
}

/** Reference model: `PublisherRegistry.Branch` - renamed, see FEATURE-COVERAGE.md §1.4 above. */
entity PublisherBranch {
  /** Generated by the server unless the request brings one - see srv/handlers/keys.ts. */
  @Core.ComputedDefaultValue
  key Id      : Integer;
      City    : String(80);
      Country : String(60);
}
